Traceback (most recent call last):
  File "/home/john/.local/lib/python3.8/site-packages/dask/distributed.py", line 11, in <module>
    from distributed import *
ModuleNotFoundError: No module named 'distributed'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/jlavelle.COMPASSINFORMAT/OneDrive - Compass Informatics/code/echoes/eo-processors/eo_processors/matchup/__main__.py", line 12, in <module>
    from dask.distributed import Client
  File "/home/john/.local/lib/python3.8/site-packages/dask/distributed.py", line 14, in <module>
    raise ImportError(_import_error_message) from e
ImportError: dask.distributed is not installed.

Please either conda or pip install distributed:

  conda install dask distributed             # either conda install
  python -m pip install "dask[distributed]" --upgrade    # or pip install
